---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::polars=1.34.0
  - conda-forge::pandas=2.3.3
  - conda-forge::matplotlib=3.10.6
  - conda-forge::pyarrow=21.0.0
  - conda-forge::4.67.1
