---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::requests=2.32.4
  - conda-forge::tqdm=4.67.1
  - conda-forge::tenacity=9.1.2
